let data=[
    {
        id:1,
        name:'Haryana',
        info:"Haryana,a vibrant state in North India,is a captivating blend of ancient history and modern progress.Its rich cultural heritage,historical significance,and bustling cities make it a fascinating destination for travelers and history enthusiasts alike.The state boasts several prominent cities,each with its unique charm and attractions.Gurgaon,also known as Gurugram,has emerged as a major technological hub,housing numerous multinational companies and IT parks.Its modern skyline,upscale malls,and vibrant nightlife make it a cosmopolitan city.Faridabad,another industrial city,is known for its manufacturing industries and engineering hubs.It offers a glimpse into Haryanas industrial prowess and development.Chandigarh,the joint capital of Haryana and Punjab,is a meticulously planned city renowned for its beautiful architecture and green spaces.Designed by the renowned architect Le Corbusier,Chandigarh's well-organized layout and iconic landmarks make it a visually appealing city.Kurukshetra,a sacred city,holds immense historical and religious significance.It is believed to be the site of the legendary Battle of Kurukshetra,described in the epic Mahabharata.The city is dotted with ancient temples,pilgrimage sites,and serene lakes,attracting devotees and history buffs alike.Haryana's cities offer a diverse range of experiences,from the bustling metropolis of Gurgaon to the serene pilgrimage sites of Kurukshetra.Whether you're interested in exploring ancient history,experiencing modern urban life,or simply immersing yourself in the vibrant culture of Haryana,these cities have something to offer everyone.",
        image:'https://images.pexels.com/photos/3938802/pexels-photo-3938802.jpeg?auto=compress&cs=tinysrgb&w=600',
        price:'35758'
    },
    {
        id:2,
        name:'Delhi',
        info:"Delhi, the vibrant capital of India, is a bustling metropolis that seamlessly blends the ancient and the modern. It is a city rich in history, with a plethora of monuments, temples, and historical sites that tell the tales of bygone eras. The magnificent Red Fort, an iconic symbol of India, stands as a testament to the Mughal Empire's grandeur. Just a stone's throw away is the Jama Masjid, one of the largest mosques in India, which attracts thousands of visitors daily. The India Gate, a war memorial dedicated to the soldiers who died in World War I, is another landmark that draws crowds, especially in the evenings when it is beautifully lit up. Delhi is also home to the bustling Chandni Chowk market, where one can experience the city's vibrant street life and shop for everything from spices to jewelry. The Qutub Minar, a UNESCO World Heritage Site, is a must-visit for history buffs, showcasing the architectural brilliance of the Sultanate period. The city's modern side is equally captivating, with areas like Connaught Place offering a wide array of shopping, dining, and entertainment options. The Lotus Temple, with its stunning architecture, and the Akshardham Temple, known for its intricate carvings, are modern marvels that add to Delhi's charm. Delhi's culinary scene is diverse and delicious, offering everything from street food like chaat and parathas to fine dining experiences. The city's well-connected metro system makes it easy to explore all these attractions. Despite its hustle and bustle, Delhi has its serene spots, such as the Lodhi Gardens and the serene Yamuna River. Whether you're a history enthusiast, a foodie, or simply looking to experience the vibrant culture of India, Delhi has something to offer for everyone.",
        image:'https://images.pexels.com/photos/169647/pexels-photo-169647.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        price:'23525'
    },
    {
        id:3,
        name:'Bhopal',
        info:"Bhopal, the capital city of Madhya Pradesh, is a fascinating blend of old and new, known for its historical monuments, lakes, and modern infrastructure. The city is famously called the City of Lakes due to its numerous natural and artificial lakes, with the Upper Lake and Lower Lake being the most prominent. These lakes provide a serene backdrop to the city and are popular spots for boating and picnics. Bhopal's rich history is evident in its magnificent mosques, such as the Taj-ul-Masajid, one of the largest mosques in India, known for its stunning architecture and spiritual ambiance. The city's Old Bhopal area is a treasure trove of historical sites, narrow lanes, bustling bazaars, and traditional havelis. The Shaukat Mahal and Sadar Manzil are notable examples of Bhopal’s architectural heritage, reflecting a blend of Indo-Islamic and European styles. The Bharat Bhavan, a multi-arts complex, is a hub for cultural activities, including theatre, art exhibitions, and music performances, showcasing the city’s vibrant cultural scene. The Van Vihar National Park, located near the Upper Lake, offers a glimpse into the region's rich biodiversity, home to a variety of flora and fauna. Bhopal's cuisine is a delightful blend of Mughlai and local flavors, with dishes like poha, biryani, and kebabs being popular among food enthusiasts. The city's markets, such as Chowk Bazaar and New Market, offer a unique shopping experience with a range of traditional crafts and textiles. Bhopal's modern infrastructure, with its educational institutions, healthcare facilities, and industrial hubs, complements its historical charm, making it a dynamic and appealing city. Whether you're exploring its historical landmarks, enjoying the tranquil lakes, or immersing yourself in its cultural activities, Bhopal offers a unique and enriching experience.",
        image:'https://images.pexels.com/photos/325185/pexels-photo-325185.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        price:'46422'
    },
    {
        id:4,
        name:'Jaipur',
        info:"Jaipur, famously known as the Pink City, is a captivating blend of heritage, culture, and vibrant colors. As the capital of Rajasthan, it is a city that offers a glimpse into India's royal past. The city's stunning architecture, from majestic palaces to ancient forts, tells tales of its glorious history. The Amber Fort, perched on a hilltop, is a marvel of Rajput architecture and offers breathtaking views of the surrounding landscape. The City Palace, located in the heart of Jaipur, is a grand complex that showcases the opulence of the royal family. Within the palace complex is the Chandra Mahal and Mubarak Mahal, each with its own unique architectural beauty. The Hawa Mahal, or the Palace of Winds, with its intricate latticework, is another iconic landmark that captivates visitors. Jaipur's Jantar Mantar, an astronomical observatory, is a UNESCO World Heritage Site and a testament to the scientific advancements of the past. The Nahargarh Fort and Jaigarh Fort offer panoramic views of the city and are popular spots for history enthusiasts. Jaipur's vibrant bazaars, such as Johari Bazaar and Bapu Bazaar, are perfect for shopping for traditional Rajasthani handicrafts, jewelry, and textiles. The city's rich cultural heritage is reflected in its festivals, with the Jaipur Literature Festival and the Teej Festival being major attractions. Jaipur's culinary scene is equally enticing, with traditional Rajasthani dishes like dal baati churma and ghewar delighting food lovers. The city's modern side is evident in its upscale hotels, cafes, and shopping malls, offering a perfect blend of the old and the new. Jaipur's warm hospitality and rich cultural tapestry make it a must-visit destination for anyone looking to experience the regal charm of Rajasthan.",
        image:'https://images.pexels.com/photos/3938802/pexels-photo-3938802.jpeg?auto=compress&cs=tinysrgb&w=600',
        price:'83567'
    },
    {
        id:5,
        name:'Sikkim',
        info:"Nestled in the lap of the Himalayas, Sikkim is a paradise for nature lovers and adventure enthusiasts alike. This northeastern state of India is renowned for its stunning landscapes, from lush green valleys and pristine lakes to snow-capped mountains. The Kanchenjunga, the third highest peak in the world, towers majestically over Sikkim, offering breathtaking views and trekking opportunities for the brave-hearted. The state's capital, Gangtok, is a vibrant town that serves as the gateway to exploring Sikkim's natural beauty. The MG Marg in Gangtok is a bustling street lined with shops, cafes, and restaurants, perfect for soaking in the local culture. Sikkim is also home to numerous monasteries, with the Rumtek Monastery being one of the most significant. This monastery is a center of Tibetan Buddhist culture and offers serene and spiritual vibes to visitors. The Tsomgo Lake, located at an altitude of 12,400 feet, is a must-visit for its crystal-clear waters and stunning surroundings. Sikkim is also famous for its hot springs, like the ones in Yumthang Valley, known for their therapeutic properties. For adventure seekers, Sikkim offers a plethora of activities such as trekking, river rafting, and paragliding. The state's rich biodiversity can be witnessed in places like the Khangchendzonga National Park, a UNESCO World Heritage Site, home to red pandas, snow leopards, and numerous bird species. Sikkim's unique cuisine, with dishes like momos and thukpa, is a delight for food enthusiasts. The state's warm and hospitable people add to the charm, making Sikkim a must-visit destination for anyone looking to experience the serenity and beauty of the Himalayas. Whether you're seeking adventure, peace, or a deep dive into Tibetan Buddhist culture, Sikkim has it all.",
        image:'https://images.pexels.com/photos/169647/pexels-photo-169647.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        price:'35363'
    },
    {
        id:6,
        name:'Punjab',
        info:"Punjab, known as the Land of Five Rivers is a vibrant state in northern India, celebrated for its rich culture, history, and fertile lands. The Golden Temple in Amritsar, a significant spiritual site for Sikhs, stands as a symbol of peace and humanity, drawing millions of visitors every year. The temple’s golden dome and the serene Amrit Sarovar (holy tank) create an atmosphere of deep tranquility. Punjab's history is deeply intertwined with the freedom struggle of India, with landmarks like the Jallianwala Bagh serving as a poignant reminder of the past. The state's cities, such as Ludhiana, Jalandhar, and Patiala, are hubs of industrial and educational activities. Ludhiana, often referred to as the Manchester of India, is famous for its hosiery industry. The lush green fields of Punjab, particularly in rural areas, are a testament to the state’s agricultural prosperity. The traditional dance forms like Bhangra and Gidda are expressions of the joyous spirit of the Punjabis, often performed during festivals and celebrations. Punjab's culinary delights, such as butter chicken, sarson da saag, and makki di roti, are globally renowned, offering a burst of flavors that reflect the state’s agricultural richness. The state's vibrant festivals, including Baisakhi and Lohri, showcase the rich traditions and communal harmony of the region. Punjab’s warm hospitality, vibrant culture, and rich history make it a unique and inviting destination. Whether you’re exploring the bustling streets of Amritsar, savoring the delicious cuisine, or dancing to the beats of Bhangra, Punjab offers an unforgettable experience that celebrates life in all its forms.",
        image:'https://images.pexels.com/photos/3938802/pexels-photo-3938802.jpeg?auto=compress&cs=tinysrgb&w=600',
        price:'76544'
    },
    {
        id:7,
        name:'Agra',
        info:"Agra, a city on the banks of the Yamuna River in Uttar Pradesh, is synonymous with the majestic Taj Mahal, one of the Seven Wonders of the World. This white marble mausoleum, built by Emperor Shah Jahan in memory of his beloved wife Mumtaz Mahal, is a UNESCO World Heritage Site and a symbol of eternal love. The intricate carvings, beautiful gardens, and the reflecting pool enhance the Taj Mahal’s ethereal beauty, especially under the moonlight. Agra’s rich history is also reflected in other monumental structures such as the Agra Fort, a massive red sandstone fortress that served as the residence of the Mughal emperors. The fort offers a glimpse into the opulent lifestyle of the Mughal dynasty, with its exquisite palaces and audience halls. The city is also home to Fatehpur Sikri, an ancient city that was once the capital of the Mughal Empire. Its well-preserved ruins offer a fascinating insight into Mughal architecture and urban planning. Agra’s bustling markets, like Sadar Bazaar and Kinari Bazaar, are perfect for shopping for local crafts, jewelry, and delicious street food. The city’s culinary scene is renowned for its Mughlai cuisine, with dishes like petha, a sweet delicacy, being a must-try for visitors. Agra’s strategic location makes it a gateway to exploring other historical sites in the region, such as Mathura and Vrindavan. The city’s blend of historical grandeur and vibrant street life offers a unique experience for visitors. Whether you are marvelling at the Taj Mahal’s beauty, exploring the historical forts, or enjoying the local cuisine, Agra provides a journey through time that is both enriching and captivating.",
        image:'https://images.pexels.com/photos/325185/pexels-photo-325185.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        price:'24345'
    },
    {
        id:8,
        name:'Leh',
        info:"Leh, the largest town in the Ladakh region, is a destination that offers unparalleled beauty and adventure. Nestled in the northernmost part of India, Leh is known for its stunning landscapes, from rugged mountains and deep valleys to crystal-clear lakes. The town is a gateway to exploring the pristine beauty of the Himalayas. The Leh Palace, reminiscent of the Potala Palace in Lhasa, offers panoramic views of the town and the surrounding mountains. The Shanti Stupa, a symbol of peace and spirituality, is another must-visit, especially at sunset when the views are breathtaking. Leh is also a base for exploring the famous Pangong Lake, which stretches from India to China and is known for its ever-changing blue hues. The Nubra Valley, with its sand dunes and Bactrian camels, offers a unique desert experience in the mountains. The Khardung La Pass, one of the highest motorable roads in the world, is a thrill for adventure seekers. Leh's monasteries, such as Hemis Monastery and Thiksey Monastery, offer a glimpse into the region's rich Buddhist heritage. The town's vibrant markets are perfect for shopping for traditional Ladakhi handicrafts and souvenirs. Leh is also a haven for trekking and mountaineering enthusiasts, with numerous trails and peaks to explore. The town's cuisine, influenced by Tibetan flavors, includes dishes like momos, thukpa, and butter tea, which are a delight for food lovers. Leh's serene and tranquil environment, coupled with its natural beauty and cultural richness, makes it a perfect destination for those looking to escape the hustle and bustle of city life. Whether you're seeking adventure, peace, or a deep dive into Himalayan culture, Leh offers an unforgettable experience.",
        image:'https://images.pexels.com/photos/169647/pexels-photo-169647.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        price:'87654'
    },

]
export default data